name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build ✨
        run: |
          npm ci
          npm run generate
          cp README.md dist/README.md
          echo "nojekyll" >> dist/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main
          FOLDER: dist
          REPOSITORY_NAME: dsrca/dsrca.github.io
          CLEAN: true
