name: deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build ✨
        run: |
          npm ci
          npm run build
          cp README.md dist/README.md
          echo "nojekyll" >> dist/.nojekyll
        env:
          GA: ${{ secrets.ENV_GA }}
          HOST: ${{ secrets.ENV_HOST }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main
          FOLDER: dist
          REPOSITORY_NAME: dsrca/dsrca.github.io
          CLEAN: true
