name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v1
        with:
          node-version: 14
          check-latest: true

      - name: Build ✨
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build
          echo "nojekyll" >> dist/.nojekyll
        env:
          GA: G-XXXXXXXXXX
          HOST: example.org
